exports.keys=[
	"Friends Ross",
	"friends chandler",
	"Rachel Green",
	"the rachel",
	"Friends",
	"Gardner Minshew",
	"titans vs jaguars",
	"Jacksonville Jaguars",
	"Jaguars",
	"Tennessee Titans",
	"Titans",
	"Thursday Night Football Week 3",
	"Minshew",
	"jaguars vs titans",
	"Marcus Mariota",
	"Rugby World Cup 2019",
	"Area 51 raid",
	"Area 51",
	"Storm Area 51",
	"Houston Weather",
	"houston flooding",
	"Houston",
	"Imelda",
	"texas flooding",
	"Texas",
	"beaumont tx",
	"houston news",
	"flooding in houston",
	"iOS 13",
	"ios 13 release date",
	"iOS 13 release time",
	"ios 13 features",
	"ios13",
	"Cardi B",
	"Jim Jones",
	"Nine Trey Bloods",
	"jim jones rapper",
	"Europa League",
	"Manchester United",
	"man united vs astana",
	"Downton Abbey",
	"Josh Turner",
	"Shia LaBeouf",
	"Katie Waldman",
	"Domingo German",
	"Sapiosexual",
	"Talk Like A Pirate Day",
	"Tulane football",
	"Call of Duty: Modern Warfare beta",
	"Megan Fox",
	"Whistleblower",
	"Kenya Moore"
]