exports.keys=[
	"iPhone 11 Pro",
	"iphone 11 price",
	"apple iphone 11",
	"iPhone 11 Pro Max",
	"trypophobia",
	"Apple Watch Series 5",
	"i phone 11",
	"new iphone release 2019",
	"iPhone XR",
	"Apple Watch",
	"iPhone 11 release date",
	"iOS 13",
	"Apple TV",
	"new iPhone 11",
	"iphone xs max",
	"new iphone 2019",
	"Apple TV Plus",
	"iphone x",
	"iphone 11 colors",
	"iPhone XS",
	"apple iphone",
	"apple watch series 4",
	"AAPL",
	"iphone 11 pro price",
	"iphone11",
	"apple keynote 2019",
	"apple news",
	"how much is the iphone 11",
	"iPhone 8",
	"Apple Arcade",
	"apple watch 5",
	"iphone pro",
	"apple announcement",
	"new apple iphone",
	"Antonio Brown",
	"britney taylor antonio brown",
	"antonio brown news",
	"britney taylor and antonio brown",
	"antonio brown trainer",
	"brittney taylor antonio brown",
	"antonio brown text messages",
	"antonio brown accuser",
	"September 11",
	"twin towers",
	"What year was 9/11",
	"Pentagon",
	"9/11 images",
	"John Bolton",
	"Bolton",
	"Mexico vs Argentina",
	"argentina vs. méxico",
	"North Carolina special election",
	"nc special election",
	"Dan Bishop",
	"Dan McCready",
	"911",
	"Jarrid Wilson",
	"Bill Nye",
	"Christian Yelich",
	"Yelich",
	"Dennis Rodman",
	"Kylie Jenner Playboy",
	"Palindrome",
	"Palindrome Week",
	"Caroline Calloway",
	"Hella Mega Tour",
	"Green Day",
	"Earthquake",
	"Neiron Ball",
	"Demaryius Thomas",
	"Cameron Mathison health",
	"cameron mathison",
	"Bill Burr",
	"iPhone 11",
	"Apple event",
	"New iPhone",
	"iPhone",
	"ios 13 release date",
	"apple event 2019",
	"apple keynote",
	"Raiders",
	"Britney Taylor",
	"Oakland Raiders",
	"jon gruden",
	"Patriots",
	"New England Patriots",
	"Josh Gordon",
	"juju smith schuster",
	"Saints",
	"New Orleans Saints",
	"Drew Brees",
	"Deshaun Watson",
	"saints vs texans",
	"DeAndre Hopkins",
	"Taysom Hill",
	"alvin kamara",
	"kenny stills",
	"9/11",
	"Calculator",
	"Broncos",
	"joe flacco",
	"Josh Jacobs",
	"raiders vs broncos",
	"Gareon Conley",
	"Derek Carr",
	"Tyrell Williams",
	"Darren Waller",
	"MAPS",
	"LinkedIn",
	"Snake",
	"Chrissy Teigen",
	"chrissy teigen twitter",
	"John Legend",
	"Sarah Palin",
	"Office 365",
	"microsoft 365",
	"Canvas",
	"Monday Night Football Week 1",
	"monday night football tonight",
	"Dictionary",
	"Finance",
	"NFL Standings",
	"USPS",
	"Yankees vs Red Sox",
	"Dave Dombrowski"
]