exports.keys=[
	"Texas shooting",
	"odessa tx",
	"Seth Ator",
	"shooting in texas",
	"odessa shooting",
	"Texas",
	"odessa texas",
	"Odessa",
	"midland shooting",
	"midland texas",
	"shooting",
	"mass shooting",
	"Seth Aaron Ator",
	"midland tx",
	"texas shooter",
	"odessa news",
	"odessa shooter",
	"odessa shooter name",
	"midland odessa",
	"Midland",
	"shooting in odessa tx today",
	"Auburn football",
	"oregon vs auburn",
	"espn college football",
	"oregon football",
	"auburn vs oregon",
	"bo nix",
	"Auburn",
	"Oregon Ducks",
	"justin herbert",
	"Dorian path",
	"dorian update",
	"Bahamas",
	"Abaco Islands",
	"strongest hurricane ever",
	"latest hurricane update",
	"Tennessee football",
	"georgia football",
	"ut football",
	"georgia state football",
	"Ohio State football",
	"ohio state football schedule",
	"Justin Fields",
	"Ohio State",
	"Alabama football",
	"Alabama",
	"Joker",
	"Joaquin Phoenix",
	"the joker",
	"South Carolina football",
	"Mack Brown",
	"UNC Football",
	"north carolina football",
	"south carolina vs unc",
	"gamecock football",
	"Jadeveon Clowney",
	"Clowney",
	"Laremy Tunsil",
	"Kenny Stills",
	"FSU football",
	"florida state football",
	"Oklahoma football",
	"USC football",
	"JT Daniels",
	"Fresno State football",
	"usc",
	"Jalen Hurts",
	"Penn State football",
	"Penn State",
	"Joker movie",
	"joker release date",
	"joker review",
	"Boise State football",
	"boise state vs florida state",
	"FSU",
	"Ncaa football",
	"college football rankings",
	"Nebraska Football",
	"south alabama vs nebraska",
	"LSU football",
	"LSU",
	"Hurricane tracker",
	"dorian track",
	"hurricanes 2019",
	"dorian storm",
	"Puerto Rico",
	"Blake Bivens",
	"Matthew Bernard",
	"Neal Casal",
	"Miley Cyrus",
	"DeMarcus Cousins",
	"Christy West",
	"Fortnite. Patch notes",
	"Paige VanZant",
	"Ilhan Omar",
	"Coco Gauff",
	"D23",
	"Rob Gronkowski",
	"Lori Loughlin",
	"Carli Lloyd",
	"Liga MX",
	"Bret Stephens",
	"D23 membership",
	"Danny Masterson",
	"Benicio Bryant",
	"Post Malone",
	"dorian path",
	"Dorian Tracker",
	"Hurricane Andrew",
	"florida map",
	"Florida",
	"map of florida",
	"hurricane dorian path",
	"hurricane categories",
	"noaa hurricane dorian",
	"european hurricane model",
	"Hurricane Dorian spaghetti models",
	"Category 4 hurricane",
	"hurricane dorian 2019 path",
	"Clemson football",
	"clemson vs georgia tech",
	"Clemson",
	"Trevor Lawrence",
	"georgia tech football",
	"Tiffany Trump",
	"Madeleine Westerhout",
	"Dallas Cowboys",
	"Ryan Russell",
	"Cowboys",
	"Naomi Osaka",
	"coco gauff us open",
	"College football schedule",
	"ncaa football",
	"ncaa football schedule",
	"College football",
	"Carnival Row",
	"Cara Delevingne",
	"Champions League draw",
	"Champions League",
	"UEFA Champions League Draw",
	"Steelers",
	"steelers vs panthers",
	"Pittsburgh Steelers",
	"ESPN College football",
	"Cleveland Browns",
	"Browns",
	"Michael Jackson",
	"Seahawks",
	"Texans",
	"Buffalo Bills",
	"Vikings",
	"Minnesota Vikings",
	"Chicago Bears",
	"Bears",
	"Saints",
	"dolphins vs saints",
	"New Orleans Saints",
	"Don't Let Go",
	"BYU football",
	"utah football",
	"Alyson Stoner",
	"Missy Elliott",
	"Lizzo",
	"Sebastian Maniscalco",
	"Normani",
	"vma winners 2019",
	"mtv music awards",
	"lizzo vma performance",
	"missy elliott vma",
	"2019 MTV Video Music Awards",
	"VMA",
	"mtv vmas 2019",
	"MTV",
	"vma 2019",
	"missy elliott vma performance",
	"National Dog Day",
	"when is national dog day",
	"Hurricane Florida",
	"noaa hurricane",
	"tropical storm",
	"Hurricane Dorian",
	"NOAA",
	"tropical storm florida",
	"Shawn Mendes",
	"Camila Cabello",
	"Shawn Mendes and Camila Cabello",
	"Halsey",
	"US Open",
	"Roger Federer",
	"Federer",
	"Sumit Nagal",
	"us open tennis 2019",
	"Serena Williams",
	"US Open Tennis",
	"Maria Sharapova",
	"Popeyes chicken sandwich",
	"Star Wars",
	"star wars trailer",
	"Rise Of Skywalker",
	"star wars the rise of skywalker",
	"Star Wars 9",
	"new star wars trailer",
	"WoW Classic",
	"classic wow",
	"World of Warcraft",
	"wow classic release date",
	"world of warcraft classic",
	"Sean Duffy",
	"Rachel Campos Duffy",
	"Dorian",
	"Dave Chappelle",
	"Louis CK",
	"US Open 2019",
	"Paul Mooney",
	"Richard Pryor Jr",
	"Yankees vs Mariners",
	"John Travolta",
	"You Need to Calm Down",
	"Cardi B",
	"Johnson and Johnson",
	"Lara Spencer",
	"Wizard of Oz",
	"The Wizard of Oz",
	"David Koch",
	"koch brothers",
	"Koch",
	"charles koch",
	"Koch Industries",
	"Disney Plus",
	"The Mandalorian",
	"Disney",
	"Mandalorian",
	"Mandalorian Trailer",
	"Moon Knight",
	"ms marvel",
	"She Hulk",
	"Yankees vs Dodgers",
	"Dwight Howard",
	"Lizzie McGuire",
	"Hilary Duff",
	"Ruth Bader Ginsburg",
	"lara spencer ballet",
	"The Eternals",
	"Kit Harington",
	"Lindsey Vonn",
	"PK Subban",
	"Barry Bennett",
	"Trump Twitter",
	"Lady and the Tramp",
	"lady and the tramp 2019",
	"Detroit Lions",
	"Seth Moulton",
	"Becky Lynch",
	"Hurricane",
	"hurricane florida",
	"hurricane dorian update",
	"National Hurricane Center",
	"Hurricane Dorian 2019",
	"hurricane dorian track",
	"florida hurricane",
	"Hurricane Dorian Tracker",
	"dorian hurricane",
	"hurricane dorian noaa",
	"hurrican dorian",
	"hurricane dorian models",
	"hurricane dorian florida",
	"noaa dorian",
	"dorian spaghetti models",
	"spaghetti models",
	"hurricane update",
	"tropical storm dorian track",
	"puerto rico hurricane",
	"Jessi Combs",
	"jessi combs accident",
	"jesse combs",
	"Mythbusters",
	"jessi combs death",
	"jessi combs crash",
	"jessi combs mythbusters",
	"jessie combs",
	"joker trailer",
	"joker movie",
	"Caty McNally",
	"Travis Scott",
	"Look Mom I Can Fly",
	"Melanie Olmstead",
	"Kirsten Gillibrand",
	"gillibrand",
	"Pokemon Masters",
	"Kevin O'Leary",
	"Boris Johnson",
	"Brexit",
	"BJ Penn",
	"CBD",
	"Gronkowski",
	"Venus Williams",
	"Steve Jobs",
	"Spaghetti models",
	"Tulsi Gabbard",
	"Prince Andrew",
	"Margaret Qualley",
	"Man of Medan",
	"Matthew McConaughey",
	"Patrick Chung",
	"Cam Newton",
	"Patriots",
	"New England Patriots",
	"Carolina Panthers",
	"Taylor Swift",
	"taylor swift lover",
	"joe alwyn",
	"lover taylor swift",
	"taylor swift boyfriend",
	"Angel Has Fallen",
	"13 Reasons Why",
	"13 Reasons Why Season 3",
	"Who Killed Bryce Walker",
	"Patrick Byrne",
	"Maria Butina",
	"overstock ceo patrick byrne",
	"Overcomer",
	"Rainbow baby",
	"Packers vs Raiders",
	"India vs West Indies",
	"Amber Alert",
	"Miami Dolphins",
	"Titanic",
	"Major Lazer",
	"Jeremy Camp",
	"Tour Championship",
	"Hasan Piker",
	"Earthquake",
	"Larry Swearingen",
	"VMAs 2019",
	"VMAs",
	"Rory McIlroy",
	"pga tour championship",
	"Brooks Koepka",
	"FedEx Cup",
	"Tropical Storm Dorian",
	"hurricane dorian 2019",
	"Barcelona vs Real Betis",
	"Barcelona",
	"FC Barcelona",
	"steelers vs titans",
	"Tennessee Titans",
	"Joe Walsh",
	"joe walsh president",
	"LAFC",
	"MLS",
	"LA Galaxy",
	"lafc vs la galaxy",
	"Delonte West",
	"Blake Lively",
	"Ryan Reynolds",
	"Aaliyah",
	"Tim Green",
	"Soma",
	"Rise of Skywalker",
	"Great Mall",
	"The Affair",
	"Peaky Blinders",
	"Gemma Chan",
	"Tottenham",
	"Chivas",
	"Andrew Luck",
	"andrew luck retire",
	"Jacoby Brissett",
	"Colts",
	"andrew luck retiring",
	"andrew luck age",
	"Indianapolis Colts",
	"nfl news",
	"andrew luck injury",
	"Andrew Luck retires",
	"Miami vs Florida",
	"Florida Gators",
	"florida vs miami",
	"Tate Martell",
	"gators vs miami",
	"miami hurricanes football",
	"miami football",
	"Feleipe Franks",
	"ncaa football scores",
	"Miami Hurricanes",
	"florida football",
	"Gators",
	"college football schedule",
	"Lamar Miller",
	"texans vs cowboys",
	"Duke Johnson",
	"cowboys vs texans",
	"Power",
	"power season 6",
	"power season 6 episode 1",
	"Thanos",
	"James Charles",
	"james charles nudes",
	"james charles nude",
	"What to watch",
	"Curacao",
	"little league world series scores",
	"LLWS",
	"Breaking Bad Movie",
	"El Camino",
	"Breaking Bad",
	"cardinals vs vikings",
	"Liverpool vs Arsenal",
	"Liverpool",
	"Saints vs Jets",
	"Emma Stone",
	"emma stone cruella de vil",
	"seattle seahawks",
	"Sofia Richie",
	"Scott Disick",
	"Hawaii football",
	"arizona vs hawaii",
	"Manchester United",
	"man united vs crystal palace",
	"Denver Broncos",
	"Broncos",
	"Eddie Money",
	"BMW",
	"Benz",
	"Apple",
	"Binance",
	"BTC",
	"PS4",
	"Sony",
	"Switch",
	"Valerie Harper",
	"Mary Tyler Moore",
	"valerie harper dead",
	"Rhoda",
	"Mar a Lago",
	"Category 5 hurricane",
	"Toyota",
	"Tyler Skaggs",
	"fentanyl",
	"LeSean McCoy",
	"nfl cuts",
	"Devin Singletary",
	"Frank Gore",
	"Michigan football",
	"Franco Columbu",
	"Arnold Schwarzenegger",
	"Toto",
	"Tool",
	"tool fear inoculum",
	"Fear Inoculum",
	"tool tour",
	"Simone Biles",
	"simone biles brother",
	"TikTok",
	"Yamaha"
]