exports.keys=[
	"Cokie Roberts",
	"cokie roberts breast cancer",
	"cokie roberts health",
	"AGT winner 2019",
	"Kodi Lee",
	"who won america's got talent",
	"Leona Lewis",
	"americas got talent finals",
	"agt finals",
	"Israel election",
	"Netanyahu",
	"israeli election results",
	"israel",
	"israeli elections",
	"israel election results",
	"Eli Manning",
	"Daniel Jones",
	"Houston weather",
	"Tropical Storm Imelda",
	"weather houston",
	"Imelda",
	"tropical storm houston",
	"Tropical Storm",
	"Barcelona",
	"dortmund vs barcelona",
	"dortmund contra barcelona",
	"FC Barcelona",
	"barcelona vs dortmund",
	"dortmund vs. barcelona",
	"Tekashi69",
	"6ix9ine",
	"Trippie Redd",
	"Amber Alert",
	"dulce alavez",
	"amber alert nj",
	"Aaron Carter",
	"Nick Carter",
	"Napoli vs Liverpool",
	"UEFA Champions League",
	"Liverpool",
	"Felipe Vazquez",
	"Corey Lewandowski",
	"Lewandowski",
	"Alex Trebek",
	"Hank Williams",
	"Julianne Hough",
	"Constitution Day",
	"Constitution",
	"Jamal Adams",
	"Jeezy",
	"Jeannie Mai",
	"Carl Yastrzemski",
	"Champions League",
	"Real Madrid",
	"PSG vs Real Madrid",
	"psg",
	"psg vs. real madrid",
	"American Horror Story",
	"ahs 1984",
	"american horror story 1984",
	"AHS 1984 cast",
	"AHS",
	"american horror story season 9 episode 1",
	"Justin Trudeau",
	"Trudeau",
	"justin trudeau blackface",
	"Cher",
	"National Cheeseburger Day",
	"Ed Buck",
	"Sirfetch'd",
	"pokemon sword and shield",
	"farfetch'd",
	"Sandy Hook Promise video",
	"Sandy Hook Promise",
	"Sandy Hook",
	"Wrinkles the Clown",
	"Juventus",
	"atlético madrid vs juventus",
	"Mollie Gates",
	"Thomas Middleditch",
	"AHS: 1984",
	"Taco Charlton",
	"Greta Thunberg",
	"Michael Folmer",
	"Mike Folmer",
	"Patsy Cline",
	"Mortgage rates",
	"Fed rate cut",
	"Interest Rates",
	"UFO",
	"South Africa vs India"
]