exports.keys=[
	"Antonio Brown",
	"Patriots",
	"Antonio Brown released",
	"antonio brown news",
	"AB",
	"Ad Astra",
	"Woodfield Mall",
	"USC Football",
	"utah football",
	"Suzanne Whang",
	"First day of fall 2019",
	"Laver Cup",
	"Prince Andrew",
	"Sylvester Stallone",
	"Misha Nonoo",
	"Between Two Ferns movie",
	"Bill Gates",
	"Tekashi 69 snitch",
	"Untitled Goose Game",
	"Boise State football",
	"Blue Jays vs Yankees",
	"Roku stock",
	"Royals vs Twins",
	"Lisa Bonet",
	"Giants vs Braves",
	"Champions League",
	"Real Madrid",
	"PSG vs Real Madrid",
	"psg",
	"psg vs. real madrid",
	"American Horror Story",
	"ahs 1984",
	"american horror story 1984",
	"AHS 1984 cast",
	"AHS",
	"american horror story season 9 episode 1",
	"Justin Trudeau",
	"Trudeau",
	"justin trudeau blackface",
	"Cher",
	"National Cheeseburger Day",
	"Ed Buck",
	"Sirfetch'd",
	"pokemon sword and shield",
	"farfetch'd",
	"Sandy Hook Promise video",
	"Sandy Hook Promise",
	"Sandy Hook",
	"Wrinkles the Clown",
	"Juventus",
	"atlético madrid vs juventus",
	"Mollie Gates",
	"Thomas Middleditch",
	"AHS: 1984",
	"Taco Charlton",
	"Greta Thunberg",
	"Michael Folmer",
	"Mike Folmer",
	"Patsy Cline",
	"Mortgage rates",
	"Fed rate cut",
	"Interest Rates",
	"UFO",
	"South Africa vs India",
	"Labor Day",
	"what is labor day",
	"Hurricane Dorian",
	"bahamas hurricane",
	"dorian hurricane",
	"Hurricane Dorian 2019 path",
	"dorian spaghetti models",
	"hurricane dorian bahamas",
	"freeport bahamas",
	"Abaco Islands",
	"hurricane dorian radar",
	"dorian bahamas",
	"abaco bahamas",
	"grand bahama island",
	"dorian storm track",
	"bahamas map",
	"hurricane dorian live",
	"hurricane dorian path map",
	"nassau bahamas",
	"the Bahamas",
	"hirricane dorian",
	"bahamas weather",
	"bahamas dorian",
	"Kevin Hart",
	"kevin hart car accident",
	"kevin hart accident",
	"Plymouth Barracuda",
	"1970 Plymouth Barracuda",
	"TikTok",
	"Toyota",
	"Oklahoma football",
	"Jalen Hurts",
	"ou football",
	"houston vs oklahoma",
	"NASCAR",
	"nascar darlington",
	"Darlington race",
	"Djokovic",
	"Novak Djokovic",
	"Roger Federer",
	"Stan Wawrinka",
	"Wawrinka",
	"Labor Day meaning",
	"labor day history",
	"Justin Verlander",
	"kate upton",
	"Verlander",
	"Serena Williams",
	"Medvedev",
	"Arsenal vs Tottenham",
	"Arsenal",
	"Salma Hayek",
	"Malik Yoba",
	"Dorian spaghetti models",
	"SNK",
	"Hurricane Katrina",
	"Villarreal vs Real Madrid",
	"Notre Dame football",
	"NOTRE DAME",
	"Louisville football",
	"notre dame vs louisville",
	"notre dame football schedule",
	"Thanos",
	"Dorian now",
	"hurricane dorian now",
	"hurricane dorian live radar",
	"noaa hurricane dorian",
	"where is the hurricane now",
	"dorian live radar",
	"Honda",
	"Piano",
	"Airlines",
	"Ed",
	"Rafael Nadal",
	"Nadal",
	"Diego Schwartzman",
	"Zverev",
	"Steven Universe Movie",
	"Steven Universe",
	"What to watch",
	"Flume",
	"flume burning man",
	"Keanu Reeves",
	"Belinda Bencic",
	"Osaka",
	"Taylor Townsend",
	"Rangers vs Yankees",
	"Chace Numata",
	"Mets vs Nationals",
	"Beyonce",
	"Trader Joe's",
	"Hurricane Juliette",
	"Tiktok",
	"Yamaha",
	"UFC 242",
	"UFC",
	"Khabib",
	"khabib poirier",
	"Khabib Nurmagomedov",
	"UFC 242 start time",
	"khabib vs poirier",
	"Dustin Poirier",
	"UFC 242 Results",
	"Tony Ferguson",
	"Conor McGregor",
	"khabib vs poirier time",
	"Abu Dhabi",
	"Bianca Andreescu",
	"Andreescu",
	"serena us open 2019",
	"us open women's final 2019",
	"Venus Williams",
	"tennis us open 2019",
	"serena williams us open 2019",
	"Serena",
	"Daniil Medvedev",
	"Berrettini",
	"Matteo Berrettini",
	"Post Malone",
	"Ozzy Osbourne",
	"post malone new album",
	"post malone hollywood's bleeding",
	"hollywood's bleeding",
	"Chandrayaan-2",
	"india moon landing",
	"ISRO",
	"chandrayaan 2 landing",
	"Robert Mugabe",
	"Mugabe",
	"Chris Duncan",
	"Demi Lovato",
	"marshall football",
	"Kehlani",
	"YG",
	"Grandparents Day 2019",
	"Ynés Mexía",
	"Iowa State football",
	"Iowa Football",
	"iowa vs iowa state",
	"Iowa Hawkeyes",
	"Penn State football",
	"Penn State",
	"pittsburgh vs penn state",
	"pitt penn state game",
	"USC football",
	"byu football",
	"BYU",
	"USC",
	"Tyson Fury",
	"fury vs wallin",
	"tyson fury fight",
	"Barcelona vs Valencia",
	"Barcelona",
	"Ansu Fati",
	"fc barcelona",
	"Alabama vs South Carolina",
	"gamecocks football",
	"Premier League",
	"epl",
	"Tennessee Vols football",
	"florida football",
	"feleipe franks injury",
	"Kyle Trask",
	"Mexican Independence Day",
	"mexico independence day",
	"UCF football",
	"stanford football",
	"UCF",
	"Charlie Culberson",
	"braves vs nationals",
	"Georgia Bulldogs",
	"arkansas state vs georgia",
	"Oklahoma Sooners",
	"oklahoma vs ucla",
	"UFC Fight Night",
	"Justin Gaethje",
	"Donald Cerrone",
	"Zooey Deschanel",
	"Jonathan Scott",
	"Real Madrid vs Levante",
	"Purdue football",
	"tcu football",
	"Ohio State vs Indiana",
	"ASU football",
	"arizona state football",
	"NFL",
	"packers vs bears",
	"NFL schedule",
	"bears vs packers",
	"Packers",
	"Chicago Bears",
	"nfl scores",
	"Green Bay Packers",
	"Bears",
	"Aaron Rodgers",
	"bears game",
	"bears packers",
	"green bay vs chicago",
	"Mitch Trubisky",
	"nfl games",
	"David Montgomery",
	"Mitchell Trubisky",
	"packers bears",
	"packers schedule",
	"what channel is the bears packers game on",
	"Jimmy Graham",
	"Aaron Jones",
	"Trubisky",
	"Eddy Pineiro",
	"bears packers game",
	"Trey Burton",
	"It: Chapter 2",
	"it chapter two",
	"IT 2",
	"bill skarsgård",
	"it movie",
	"Bill Hader",
	"it chapter 2 review",
	"Kylie Rae Harris",
	"kylie rae harris songs",
	"country singer died",
	"kylie rae harris twenty years from now",
	"Nicki Minaj",
	"nicki minaj retire",
	"bencic",
	"Antonio Brown news",
	"Mike Davis 10TV",
	"Mike Davis",
	"Antonio Brown Instagram",
	"antonio brown suspension",
	"2K20",
	"Sharpie gate",
	"trump sharpie",
	"Julio Jones",
	"CHARLESTON, S.C",
	"Skai Jackson",
	"Lil Nas X",
	"Football",
	"Cubs vs Brewers",
	"Freddie Mercury",
	"Drew Brees",
	"NBC",
	"NBC Sports",
	"Joe Biden",
	"Christie Brinkley",
	"Dancing with the Stars",
	"dancing with the stars 2019",
	"Sailor Brinkley",
	"sailor brinkley cook",
	"dancing with the stars cast",
	"Jalen Ramsey",
	"Shane Gillis",
	"Bachelor in Paradise",
	"bachelor in paradise finale",
	"bachelor in paradise season 6 episode 13",
	"Minkah Fitzpatrick",
	"Sean Spicer",
	"dwts cast 2019",
	"3 From Hell",
	"rob zombie",
	"Montia Sabbag",
	"Brian Turk",
	"James Van Der Beek",
	"Colin Kaepernick",
	"Dog the Bounty Hunter",
	"Hannah Brown",
	"hannah brown dancing with the stars",
	"Trace Lysette",
	"Walmart car seat trade-in",
	"Lamar Odom",
	"Ray Lewis",
	"GM strike",
	"Eddie Money",
	"eddie money take me home tonight",
	"eddie money death",
	"eddie money two tickets to paradise",
	"Take Me Home Tonight",
	"Felicity Huffman",
	"lori loughlin",
	"william h. macy",
	"william h macy",
	"felicity huffman husband",
	"Huffman",
	"Borderlands 3",
	"Borderlands 3 Shift Codes",
	"borderlands 3 characters",
	"Rihanna",
	"Rihanna Pregnant",
	"Is Rihanna Pregnant",
	"Ava Michelle",
	"Tall Girl",
	"tall girl movie",
	"The Goldfinch",
	"Unbelievable",
	"Don't Call Me Angel",
	"charlie's angels",
	"dont call me angel",
	"Alabama football schedule 2019",
	"Wake Forest Football",
	"unc football",
	"Zantac",
	"zantac cancer",
	"Liga MX",
	"Kylie Jenner Playboy",
	"Moon tonight",
	"what is a harvest moon",
	"Brooke Richardson",
	"Skylar Richardson",
	"Shaun Livingston",
	"Cam Newton outfit",
	"Yankees vs Blue Jays",
	"Boston College football",
	"ku football",
	"iPhone 11",
	"Apple event",
	"New iPhone",
	"iPhone",
	"ios 13 release date",
	"apple event 2019",
	"apple keynote",
	"Raiders",
	"Britney Taylor",
	"Oakland Raiders",
	"jon gruden",
	"New England Patriots",
	"Josh Gordon",
	"juju smith schuster",
	"Saints",
	"New Orleans Saints",
	"Deshaun Watson",
	"saints vs texans",
	"DeAndre Hopkins",
	"Taysom Hill",
	"alvin kamara",
	"kenny stills",
	"9/11",
	"Calculator",
	"Broncos",
	"joe flacco",
	"Josh Jacobs",
	"raiders vs broncos",
	"Gareon Conley",
	"Derek Carr",
	"Tyrell Williams",
	"Darren Waller",
	"MAPS",
	"LinkedIn",
	"Snake",
	"Chrissy Teigen",
	"chrissy teigen twitter",
	"John Legend",
	"Sarah Palin",
	"Office 365",
	"microsoft 365",
	"Canvas",
	"Monday Night Football Week 1",
	"monday night football tonight",
	"Dictionary",
	"Finance",
	"NFL Standings",
	"USPS",
	"Yankees vs Red Sox",
	"Dave Dombrowski",
	"Dallas Cowboys",
	"giants vs cowboys",
	"Cowboys",
	"Giants",
	"jason witten",
	"kellen moore",
	"NY Giants",
	"eli manning",
	"Dak Prescott",
	"New York Giants",
	"saquon barkley",
	"randall cobb",
	"cowboys score",
	"cowboys vs giants",
	"Daniel Jones",
	"amari cooper",
	"Nick Foles",
	"Tyreek Hill",
	"Chiefs",
	"Kansas City Chiefs",
	"chiefs vs jaguars",
	"Patrick Mahomes",
	"Gardner Minshew",
	"Jacksonville Jaguars",
	"kc chiefs",
	"sammy watkins",
	"Jaguars",
	"nick foles injury",
	"Myles Jack",
	"Mahomes",
	"Josh Dobbs",
	"tyreek hill injury",
	"nfl power rankings",
	"Eagles",
	"redskins vs eagles",
	"Redskins",
	"Philadelphia Eagles",
	"DeSean Jackson",
	"Washington Redskins",
	"Adrian Peterson",
	"Mike Scott",
	"Vernon Davis",
	"Case Keenum",
	"Carson Wentz",
	"eagles vs redskins",
	"Google Docs",
	"docs",
	"Cleveland Browns",
	"Browns",
	"Tennessee Titans",
	"Odell Beckham",
	"Titans",
	"Derrick Henry",
	"browns vs titans",
	"Miami Dolphins",
	"Ravens",
	"Lamar Jackson",
	"Ravens vs Dolphins",
	"Baltimore Ravens",
	"Dolphins",
	"Marquise Brown",
	"hollywood brown",
	"broncos vs raiders",
	"denver broncos",
	"Seahawks",
	"Seattle Seahawks",
	"Bengals vs Seahawks",
	"Bengals",
	"joe mixon",
	"Cincinnati Bengals",
	"Russell Wilson",
	"DK Metcalf",
	"Texans vs Saints",
	"Texans",
	"Houston Texans",
	"mnf",
	"jj watt",
	"us open men's final",
	"Detroit Lions",
	"arizona cardinals",
	"Lions",
	"Kyler Murray",
	"cardinals nfl",
	"larry fitzgerald",
	"Vikings",
	"falcons vs vikings",
	"Minnesota Vikings",
	"atlanta falcons",
	"Falcons",
	"mn vikings",
	"Stefon Diggs",
	"vikings game",
	"49ers",
	"49ers vs buccaneers",
	"tampa bay bucs",
	"San Francisco 49ers",
	"Mike Evans",
	"Jameis Winston",
	"Tevin Coleman",
	"Tampa Bay Buccaneers",
	"Monday Night Football",
	"Rams vs Panthers",
	"Carolina Panthers",
	"Panthers",
	"Todd Gurley",
	"cam newton",
	"Eric Weddle",
	"Christian McCaffrey",
	"nfl football",
	"Colts",
	"Chargers",
	"colts vs chargers",
	"Adam Vinatieri",
	"indianapolis colts",
	"jacoby brissett",
	"Los Angeles Chargers",
	"Jets",
	"Buffalo Bills",
	"ny jets",
	"New York Jets",
	"le'veon bell",
	"Josh Allen",
	"steelers vs patriots",
	"Steelers",
	"Pittsburgh Steelers",
	"tom brady",
	"Sunday Night Football",
	"ben roethlisberger",
	"patriots vs steelers",
	"steelers schedule",
	"Julian Edelman",
	"patriots score",
	"Gronkowski",
	"patriots game",
	"steelers score",
	"steelers game",
	"new england patriots schedule",
	"antonio brown patriots",
	"antonio brown twitter",
	"patriots news",
	"Clemson football",
	"lsu football",
	"college football games today",
	"Clemson",
	"texas a&m football",
	"texas football",
	"LSU",
	"College football rankings",
	"texas a&m vs clemson",
	"clemson vs texas a&m",
	"Trevor Lawrence",
	"texas lsu",
	"texas a&m",
	"lsu texas",
	"Randy Moss",
	"is antonio brown playing tonight",
	"antonio brown released",
	"Michigan football",
	"army vs michigan",
	"army football",
	"Michigan",
	"michigan vs army",
	"army michigan",
	"patriots schedule",
	"LSU vs Texas",
	"Texas Longhorns",
	"Joe Burrow",
	"texas vs lsu",
	"Matthew McConaughey",
	"Sam Ehlinger",
	"Camilo Sesto",
	"camilo sesto murio",
	"AP Top 25",
	"BYU football",
	"byu vs tennessee",
	"Michigan State football",
	"msu football",
	"Mac Miller",
	"mac miller death",
	"Wisconsin football",
	"badger football",
	"Wisconsin Badgers",
	"Maryland football",
	"Syracuse Football",
	"Florida Gators",
	"gator football",
	"Miami Hurricanes",
	"Miami football",
	"Federer",
	"Monfils",
	"federer us open 2019",
	"elina svitolina",
	"Schwartzman",
	"Nintendo Direct",
	"Nintendo",
	"nintendo direct september 2019",
	"Zeke",
	"zeke elliott",
	"zeke elliott deal",
	"Boris Johnson",
	"Brexit",
	"Grigor Dimitrov",
	"Dimitrov",
	"Simone Biles",
	"simone biles brother",
	"Ariana Grande Forever 21",
	"forever 21 ariana grande",
	"Kristen Stewart",
	"Robert Pattinson",
	"USA Basketball",
	"usa vs turkey",
	"Nalani Johnson",
	"Xenophobia",
	"Jared Goff",
	"Jojo Rabbit",
	"Haley Smith",
	"Britney Spears",
	"Android 10",
	"Linda Hamilton",
	"Southwest Airline",
	"Democratic debate",
	"Elizabeth Warren",
	"Bernie Sanders",
	"Debate",
	"debate tonight",
	"Cory Booker",
	"Julian Castro",
	"democratic debate time",
	"presidential debate",
	"ABC",
	"Amy Klobuchar",
	"dem debate",
	"Democratic candidates",
	"democratic presidential debates schedule",
	"democratic polls",
	"what time is the democratic debate on thursday",
	"Events",
	"Daniel Johnston",
	"T. Boone Pickens",
	"Boone Pickens",
	"t. boone pickens",
	"How many people died in 9/11",
	"usa vs france",
	"serbia vs usa",
	"Sioux Falls tornado",
	"Sioux Falls",
	"Petara Cordero",
	"Hunter Henry",
	"9/11 Timeline",
	"Osama bin Laden",
	"World Trade Center",
	"Flight 93",
	"Breckynn Willis",
	"OneRepublic",
	"Ilhan Omar",
	"Fortnite patch notes",
	"What year was 9/11",
	"Chris Smith Browns",
	"Tornado warning",
	"Rugby World Cup 2019",
	"Rugby World Cup 2019 fixtures",
	"Area 51 raid",
	"Area 51",
	"area 51 live stream",
	"area 51 raid countdown",
	"the rachel",
	"area 51 raid live stream",
	"Storm Area 51",
	"area 51 raid live",
	"area 51 raid date",
	"storm area 51 live stream",
	"raid area 51",
	"Naruto Run",
	"when is the area 51 raid",
	"where is area 51",
	"when is the area 51 raid date",
	"what time is the area 51 raid",
	"storming area 51 live",
	"Alienstock",
	"area 51 news",
	"area 51 raid nevada",
	"Friends Ross",
	"friends rachel",
	"friends chandler",
	"Friends",
	"rachel friends",
	"titans vs jaguars",
	"Thursday Night Football Week 3",
	"Minshew",
	"Marcus Mariota",
	"Tekashi69",
	"6ix9ine",
	"Cardi B",
	"Jim Jones",
	"Nine Trey Bloods",
	"jim jones rapper",
	"6ix9ine testimony",
	"Houston Weather",
	"houston flooding",
	"Houston",
	"Imelda",
	"texas flooding",
	"Texas",
	"beaumont tx",
	"houston news",
	"flooding in houston",
	"iOS 13",
	"iOS 13 release time",
	"ios 13 features",
	"ios13",
	"Climate Strike",
	"global climate strike",
	"Climate Strike NYC",
	"climate strike september 20",
	"Downton Abbey",
	"Sapiosexual",
	"Mark Ronson",
	"Europa League",
	"Manchester United",
	"man united vs astana",
	"Hunter Biden",
	"Whistleblower",
	"Rudy Giuliani",
	"Friends Janice",
	"Josh Turner",
	"Shia LaBeouf",
	"Domingo German",
	"Katie Waldman",
	"Houston TranStar",
	"Tulane football",
	"Link's Awakening",
	"Mike Mayock",
	"antonio brown instagram",
	"antonio brown suspended",
	"Cameron James Pettit",
	"fentanyl",
	"Terry Bogard",
	"sans smash bros",
	"sans",
	"Fatal Fury",
	"sans smash",
	"sans in smash",
	"Brock Turner",
	"Chanel Miller",
	"nadal us open 2019",
	"Clint Eastwood",
	"LaShawn",
	"LaShawn Daniels",
	"Murrieta Fire",
	"Tenaja fire",
	"beyonce birthday",
	"Bad Boys 3",
	"Bad Boys for Life",
	"Peter Lindbergh",
	"Washington Nationals",
	"Wu-Tang Clan",
	"wu tang hulu",
	"Charlie Puth",
	"FIBA World Cup",
	"Orlando Bloom",
	"Gianna Santos",
	"Porsche Taycan",
	"Hustlers",
	"Ric Ocasek",
	"Paulina Porizkova",
	"The Cars",
	"rick ocassic",
	"ric ocasek wife",
	"the cars songs",
	"rick ocasek",
	"saints vs rams",
	"new orleans saints",
	"Rams",
	"Teddy Bridgewater",
	"drew brees injured",
	"drew brees injury",
	"rams vs saints",
	"Los Angeles Rams",
	"Brees",
	"seahawks vs steelers",
	"Ben Roethlisberger",
	"Mason Rudolph",
	"ben roethlisberger injured",
	"James Conner",
	"Roethlisberger",
	"steelers vs seahawks",
	"B.B. King",
	"BB King",
	"Bears vs Broncos",
	"Denver Broncos",
	"Cowboys vs Redskins",
	"redskins vs cowboys",
	"Devin Smith",
	"Michael Gallup",
	"packers vs vikings",
	"chiefs vs raiders",
	"Demarcus Robinson",
	"Patriots VS Dolphins",
	"Kavanaugh",
	"Brett Kavanaugh",
	"brett kavanaugh supreme court",
	"brett kavanaugh news",
	"WWE",
	"Clash of Champions",
	"Clash of Champions results",
	"WWE Clash of Champions",
	"bills vs giants",
	"Ireland Baldwin",
	"Alec Baldwin",
	"alec baldwin roast",
	"49ers vs Bengals",
	"Oil prices",
	"Iran",
	"saudi arabia oil attack",
	"saudi oil attack",
	"chargers vs lions",
	"Unbelievable Netflix",
	"Robert De Niro",
	"Red Sox vs Phillies",
	"iPhone 11 Pro",
	"iphone 11 price",
	"apple iphone 11",
	"iPhone 11 Pro Max",
	"trypophobia",
	"Apple Watch Series 5",
	"i phone 11",
	"new iphone release 2019",
	"iPhone XR",
	"Apple Watch",
	"iPhone 11 release date",
	"Apple TV",
	"new iPhone 11",
	"iphone xs max",
	"new iphone 2019",
	"Apple TV Plus",
	"iphone x",
	"iphone 11 colors",
	"iPhone XS",
	"apple iphone",
	"apple watch series 4",
	"AAPL",
	"iphone 11 pro price",
	"iphone11",
	"apple keynote 2019",
	"apple news",
	"how much is the iphone 11",
	"iPhone 8",
	"Apple Arcade",
	"apple watch 5",
	"iphone pro",
	"apple announcement",
	"new apple iphone",
	"britney taylor antonio brown",
	"britney taylor and antonio brown",
	"antonio brown trainer",
	"brittney taylor antonio brown",
	"antonio brown text messages",
	"antonio brown accuser",
	"September 11",
	"twin towers",
	"Pentagon",
	"9/11 images",
	"John Bolton",
	"Bolton",
	"Mexico vs Argentina",
	"argentina vs. méxico",
	"North Carolina special election",
	"nc special election",
	"Dan Bishop",
	"Dan McCready",
	"911",
	"Jarrid Wilson",
	"Bill Nye",
	"Christian Yelich",
	"Yelich",
	"Dennis Rodman",
	"Palindrome",
	"Palindrome Week",
	"Caroline Calloway",
	"Hella Mega Tour",
	"Green Day",
	"Earthquake",
	"Neiron Ball",
	"Demaryius Thomas",
	"Cameron Mathison health",
	"cameron mathison",
	"Bill Burr",
	"Thursday Night Football",
	"buccaneers vs panthers",
	"Cam Newton",
	"panthers vs buccaneers",
	"NFL Network",
	"Thursday Night Football Week 2",
	"cam newton outfit",
	"Buccaneers",
	"bucs vs panthers",
	"Greg Olsen",
	"Friday the 13th",
	"Harvest Moon",
	"full moon friday the 13th",
	"harvest moon 2019",
	"Full Moon",
	"friday the 13th full moon",
	"full moon september 13 2019",
	"Sam Darnold",
	"mononucleosis",
	"mono",
	"leveon bell",
	"trevor siemian",
	"Box",
	"Andrew Yang",
	"yang 2020",
	"Beto O'Rourke",
	"Briscoe Cain",
	"beto o'rourke",
	"Camila Cabello",
	"Shawn Mendes",
	"Vaping",
	"Juul",
	"Tropical Storm Humberto",
	"tropical storm",
	"Pete Buttigieg",
	"Demi Moore",
	"bowen yang",
	"Mike Sorrentino",
	"mike the situation",
	"Paul Walker",
	"Married at First Sight",
	"The I-Land",
	"Kristin Cavallari",
	"Andrew McCabe",
	"Cokie Roberts",
	"cokie roberts breast cancer",
	"cokie roberts health",
	"AGT winner 2019",
	"Kodi Lee",
	"who won america's got talent",
	"Leona Lewis",
	"americas got talent finals",
	"agt finals",
	"Israel election",
	"Netanyahu",
	"israeli election results",
	"israel",
	"israeli elections",
	"israel election results",
	"Eli Manning",
	"Houston weather",
	"Tropical Storm Imelda",
	"weather houston",
	"tropical storm houston",
	"Tropical Storm",
	"dortmund vs barcelona",
	"dortmund contra barcelona",
	"FC Barcelona",
	"barcelona vs dortmund",
	"dortmund vs. barcelona",
	"Trippie Redd",
	"Amber Alert",
	"dulce alavez",
	"amber alert nj",
	"Aaron Carter",
	"Nick Carter",
	"Napoli vs Liverpool",
	"UEFA Champions League",
	"Liverpool",
	"Felipe Vazquez",
	"Corey Lewandowski",
	"Lewandowski",
	"Alex Trebek",
	"Hank Williams",
	"Julianne Hough",
	"Constitution Day",
	"Constitution",
	"Jamal Adams",
	"Jeezy",
	"Jeannie Mai",
	"Carl Yastrzemski"
]