exports.keys=[
	"colts",
	"colts vs titans",
	"jacksonville jaguars vs titans",
	"nfl",
	"jacksonville jaguars",
	"patriots vs jaguars",
	"colts vs jaguars",
	"patriots vs titans",
	"jaguars vs texans",
	"jaguars vs steelers",
	"nfl titans vs jaguars",
	"titans vs texans",
	"jaguars vs tennessee titans",
	"jacksonville",
	"tennessee titans",
	"panthers",
	"eagles vs titans",
	"seahawks",
	"jaguars vs titans predictions",
	"jacksonville jaguars vs tennessee titans",
	"titans football",
	"49ers",
	"colts vs texans",
	"bills vs dolphins",
	"titans vs jaguars score",
	"nfl jacksonville jaguars",
	"nfl jaguars",
	"jacksonville jaguars schedule",
	"jaguars schedule",
	"the jacksonville jaguars",
	"football jacksonville jaguars",
	"jaguars roster",
	"jacksonville jaguars roster",
	"jaguars news",
	"jacksonville jaguars stadium",
	"jacksonville news",
	"jacksonville jaguars game",
	"jacksonville florida",
	"jacksonville jaguars news",
	"jacksonville jaguars tickets",
	"jacksonville fl",
	"patriots",
	"jacksonville jaguars depth chart",
	"jacksonville jaguars draft",
	"titans",
	"miami dolphins",
	"steelers",
	"texans",
	"eagles"
]